name: build mosaic scala
description: build mosaic scala
inputs: 
  skip_tests:
    description: 'Skip Scala Tests? true or false'
    default: 'false'
runs:
  using: "composite"
  steps:
        - name: Configure JDK
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'zulu'
        - name: Configure python interpreter
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python }}
        - name: Add packaged GDAL dependencies
          shell: bash
          run : |
            sudo apt-get update && sudo apt-get install -y unixodbc libcurl3-gnutls libsnappy-dev libopenjp2-7 
            pip install databricks-mosaic-gdal==${{ matrix.gdal }}
            sudo tar -xf /opt/hostedtoolcache/Python/${{ matrix.python }}/x64/lib/python3.9/site-packages/databricks-mosaic-gdal/resources/gdal-${{ matrix.gdal }}-filetree.tar.xz -C /
            sudo tar -xhf /opt/hostedtoolcache/Python/${{ matrix.python }}/x64/lib/python3.9/site-packages/databricks-mosaic-gdal/resources/gdal-${{ matrix.gdal }}-symlinks.tar.xz -C /
        - name: Test and build the scala JAR - skip tests is false
          if: inputs.skip_tests == 'false'
          shell: bash
          run: sudo mvn -q clean install
        - name: Build the scala JAR - skip tests is true
          if: inputs.skip_tests == 'true'
          shell: bash
          run: sudo mvn -q clean install -DskipTests -Dscoverage.skip
        - name: Publish test coverage
          if: inputs.skip_tests == 'false'
          uses: codecov/codecov-action@v1
        - name: Copy Scala artifacts to GH Actions run
          shell: bash
          run: |
            mkdir staging
            cp target/mosaic*.jar staging
